version: '3.8'
services:
  force-attach:
    image: bash
    command: tail -f /dev/null
  api:
    build:
      context: /home/morgan-freeman/Workspace/Genesis-Crawler
      dockerfile: /home/morgan-freeman/Workspace/Genesis-Crawler/dockerFiles/api_docker
    ports:
      - '8000:8000'
    depends_on:
      - mongo
      - redis_server
      - 'tor-extend-1'
    environment:
      - S_TOR_INSTANCE_COUNT=1
      - TOR_INSTANCES=1
    deploy:
      resources:
        limits:
          memory: 50G
    restart: always
    volumes:
      - /home/morgan-freeman/Workspace/Genesis-Crawler/app/:/app
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    networks:
      backend:
        ipv4_address: 172.0.0.2
  redis_server:
    image: redis
    logging:
      driver: none
    command: redis-server --requirepass killprg1
    restart: always
    networks:
      backend:
        ipv4_address: 172.0.0.3
  mongo:
    image: 'mongocamp/mongodb:5.0.9'
    container_name: mongo-db
    command: mongod --quiet --logpath /dev/null
    logging:
      driver: none
    volumes:
      - /home/morgan-freeman/Workspace/Genesis-Crawler/data/db:/data/db
    ports:
      - '27017:27017'
    restart: always
    networks:
      backend:
        ipv4_address: 172.0.0.4
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
