version: '3.8'
services:
  tor-extend-1:
    container_name: tor_instance_1
    image: barneybuffet/tor:latest
    volumes:
      - ~/Documents/docker/tor_test:/tor1
    ports:
      - '9182:9182'
      - '9183:9183'
    environment:
      PUID: '20002'
      PGID: '20003'
      TOR_CONFIG_OVERWRITE: 'true'
      TOR_LOG_CONFIG: 'true'
      TOR_PROXYL: 'true'
      TOR_PROXY_PORT: '0.0.0.0:9182'
      TOR_CONTROL_PORT: '0.0.0.0:9183'
      TOR_PROXY_SOCKET: 'true'
      TOR_PROXY_ACCEPT: 'accept 172.0.0.0/24,accept 127.0.0.1,accept 10.0.0.0/8,accept 172.16.0.0/12,accept 192.168.0.0/16'
      TOR_CONTROL: 'true'
      TOR_CONTROL_SOCKET: 'true'
      TOR_CONTROL_PASSWORD: 'Imammehdi@00'
      TOR_CONTROL_COOKIE: 'true'
      TOR_RELAY: 'false'
    networks:
      backend:
        ipv4_address: 172.0.0.5
networks:
  backend:
    ipam:
      config:
        - subnet: 172.0.0.0/24
