import enum

class TOPIC_CLASSFIER_COMMANDS(enum.Enum):
    S_LOAD_CLASSIFIER = 1
    S_PREDICT_CLASSIFIER = 2
    S_CLEAN_CLASSIFIER = 3

class TOPIC_CLASSFIER_MODEL(enum.Enum):
    S_LOAD_CLASSIFIER = 1
    S_PREDICT_CLASSIFIER = 2
    S_CLEAN_CLASSIFIER = 3

class TOPIC_CLASSFIER_TRAINER(enum.Enum):
    S_CLEAN_DATA = 2
    TOXIC_MODEL:str = "./raw/toxic_model/"

class TOPIC_CLASSFIER_MESSAGES:
    S_CLASSIFIER_NOT_TRAINED = "CLASSIFIER NOT TRAINIED"

class TOPIC_CATEGORIES:
    S_THREAD_CATEGORY_GENERAL = "general"
    S_THREAD_CATEGORY_UNKNOWN = "unknown"
    S_THREAD_CATEGORY_ILLEGAL = "illegal"
